1)SELECT W.FIRSTNAME||''||W.LASTNAME FROM WORKER W WHERE W.DEPARTMENTID='3' and W.salary>30000;

2)SELECT * FROM PROJECT WHERE BUDGET>350000;

3)

4)SELECT W.FIRSTNAME||''||W.LASTNAME FROM WORKER AS W INNER JOIN ASSIGN AS A ON W.EMPID=A.EMPID WHERE PROJNO='1019';


5)SELECT AVG(salary) FROM WORKER; SELECT FIRSTNAME||''||LASTNAME FROM WORKER
WHERE DEPARTMENTID=3 AND SALARY> 50666.666;


6)SELECT * FROM PROJECT WHERE EXPECTEDDURATIONWEEKS=(SELECT MIN(EXPECTEDDURATIONWEEKS)FROM PROJECT);
 
    
7) SELECT W.FIRSTNAME||''||W.LASTNAME FROM  
    
    
8)SELECT W.FIRSTNAME||''||W.LASTNAME FROM WORKERS W INNER JOIN ASSIGN AS A ON W.EMPID=A.EMPID INNER JOIN PROJECT AS P ON P.PROJNO=A.PROJNO
WHERE P.PROJMGRID='Liu' ORDER BY W.LASTNAME;

9)CREATE VIEW QUESTION_9 AS SELECT P.PROJNO,P.PROJNAME,W.FIRSTNAME,W.LASTNAME,W.EMPID FROM PROJECT AS P INNER JOIN
ASSIGN AS A ON A.PROJNO=P.PROJNO INNER JOIN WORKER AS W ON W.EMPID=A.EMPID;

10) SELECT COUNT(PROJNO) AS NUM_OF_PROJECTS FROM QUESTION_9 WHERE EMPID='103';
